# Contains dictionaries that map braille to English letters.

# http://www.duxburysystems.org/ximages/ueb_black8.pdf?type=8

# the alphabet
letters_A = {
        chr(10241): 'a',
        chr(10243): 'b',
        chr(10249): 'c',
        chr(10265): 'd',
        chr(10257): 'e',
        chr(10251): 'f',
        chr(10267): 'g',
        chr(10259): 'h',
        chr(10250): 'i',
        chr(10266): 'j',
        chr(10245): 'k',
        chr(10247): 'l',
        chr(10253): 'm',
        chr(10269): 'n',
        chr(10261): 'o',
        chr(10255): 'p',
        chr(10271): 'q',
        chr(10263): 'r',
        chr(10254): 's',
        chr(10270): 't',
        chr(10277): 'u',
        chr(10279): 'v',
        chr(10298): 'w',
        chr(10285): 'x',
        chr(10301): 'y',
        chr(10293): 'z',
        }

# these are things that can be within a bigger word (or their own word)
# that are aliased
sub_aliases = {
        'about'       : 'ab',
        'above'       : 'abv',
        'according'   : 'ac',
        'across'      : 'acr',
        'after'       : 'af',
        'afternoon'   : 'afn',
        'afterward',  : 'afw',
        'again',      : 'ag',
        'against',    : 'ag' + chr(),
        'almost',     : 'alm',
        'already',    : 'alr',
        'also',       : 'al',
        'although',   : 'al' + chr(),
        'altogether', : 'alt',
        'always',     : 'alw',
        'because',    : chr() + 'c',
        'before',     : chr() + 'f',
        'behind',     : chr() + 'h',
        'beneath',    : chr() + 'n',
        'beside',     : chr() + 's',
        'between',    : chr() + 't',
        'beyond',     : chr() + 'y',
        'blind',      : 'bl',
        'braille',    : 'brl',
        'cannot',     : chr() + 'c',
        'ch',         : chr(),
        'character',  : chr() + chr(),
        'children',   : chr() + 'n',
        'conceive',   : chr() + 'cv',
        'conceiving', : chr() + 'cvg',
        'could',      : 'cd',
        'day',        : chr() + 'd',
        'deceive',    : 'dcv',
        'deceivng',   : 'dcvg',
        'declare',    : 'dcl',
        'declaring',  : 'dclg',
        'ed',         : chr(),
        'either',     : 'ei',
        'en',         : chr(),
        'er',         : chr(),
        'ever',       : chr() + 'e',
        'father',     : chr() + 'f',
        'first',      : 'f' + chr(),
        'for',        : chr(),
        'friend',     : 'fr',
        'gh',         : chr(),
        'good',       : 'gd',
        'great',      : 'grt',
        'had',        : chr() + 'h',
        'here',       : chr() + 'h',
        'herself',    : 'h' + chr() + 'f',
        'him',        : 'hm',
        'himself',    : 'hmf',
        'immediate',  : 'imm',
        'in',         : chr(),
        'ing',        : chr(),
        'itself',     : 'xf',
        'know',       : chr() + 'k',
        'letter',     : 'lr',
        'little',     : 'll',
        'lord',       : chr() + 'l',
        'many',       : chr() + 'm',
        'mother',     : chr() + 'm',
        'much',       : 'm' + chr(),
        'must',       : 'm' + chr(),
        'myself',     : 'myf',
        'name',       : chr() + 'n',
        'necessary',  : 'nec',
        'neither',    : 'nei',
        'of',         : chr(),
        'one',        : chr() + 'o',
        'oneself',    : chr() + 'of',
        'ou',         : chr(),
        'ought',      : chr() + chr(),
        'ourselves',  : chr() + 'rvs',
        'ow',         : chr(),
        'paid',       : 'pd',
        'part',       : chr() + 'p',
        'perceive',   : 'p' + chr() + 'cv',
        'perceiving', : 'p' + chr() + 'cvg',
        'perhaps',    : 'p' + chr() + 'h',
        'question',   : chr() + 'q',
        'quick',      : 'qk',
        'receive',    : 'rcv',
        'receiving',  : 'rcvg',
        'rejoice',    : 'rjc',
        'rejoicing',  : 'rjcg',
        'right',      : chr() + 'r',
        'said',       : 'sd',
        'sh',         : chr(),
        'should',     : chr() + 'd',
        'some',       : chr() + 's',
        'spirit',     : chr() + 's',
        'st',         : chr(),
        'such',       : 's' + chr(),
        'th',         : chr(),
        'the',        : chr(),
        'their',      : chr() + chr(),
        'themselves', : chr() + 'mvs',
        'there',      : chr() + chr(),
        'these',      : chr() + chr(),
        'those',      : chr() + chr(),
        'through',    : chr() + chr(),
        'thyself',    : chr() + 'yf',
        'time',       : chr() + 't',
        'today',      : 'td',
        'together',   : 'tgr',
        'tomorrow',   : 'tm',
        'tonight',    : 'tn',
        'under',      : chr() + 'u',
        'upon',       : chr() + 'u',
        'wh',         : chr(),
        'where',      : chr() + chr(),
        'whose',      : chr() + chr(),
        'with',       : chr(),
        'word',       : chr() + 'w',
        'work',       : chr() + 'w',
        'would',      : 'wd',
        'young',      : chr() + 'y',
        'your',       : 'yr',
        'yourself',   : 'yrf',
        'yourselves', : 'yrvs',
        }

# these are things that must be full words to get aliased
word_aliases = {
        'as',          : 'z',
        'be',          : chr(),
        'but',         : 'b',
        'can',         : 'c',
        'child',       : chr(),
        'do',          : 'd',
        'enough',      : chr(),
        'every',       : 'e',
        'from',        : 'f',
        'go',          : 'g',
        'have',        : 'h',
        'his',         : chr(),
        'it',          : 'x',
        'its',         : 'xs',
        'just',        : 'j',
        'knowledge',   : 'k',
        'like',        : 'l',
        'more',        : 'm',
        'not',         : 'n',
        'out',         : chr(),
        'people',      : 'p',
        'quite',       : 'q',
        'rather',      : 'r',
        'shall',       : chr(),
        'so',          : 's',
        'still',       : chr(),
        'that',        : 't',
        'this',        : chr(),
        'us',          : 's',
        'very',        : 'v',
        'was',         : chr(),
        'were',        : chr(),
        'which',       : chr(),
        'will',        : 'w',
        'you',         : 'y',
        '',       : '',
        '',       : '',
        '',       : '',
        '',       : '',
        }

contractions_A = {
        chr(10293): 'as',
        chr(10287): 'and',
        chr(10243): 'but',
        chr(10249): 'can',
        chr(10265): 'do',
        chr(10257): 'every',
        chr(10303): 'for', # remove ?
        chr(10251): 'from',
        chr(10267): 'go',
        chr(10259): 'have', # rem ?
        chr(10278): 'his',
        chr(10260): 'in',
        chr(10285): 'it',
        chr(10266): 'just',
        chr(10280): 'knowledge', # rem ?
        chr(10296): 'like',
        chr(10253): 'more',
        chr(10269): 'not',
        chr(10295): 'of',
        chr(10255): 'people',
        chr(10271): 'quite',
        chr(10263): 'rather',
        chr(10254): 'so',
        chr(10270): 'that',
        chr(10286): 'the',
        chr(10262): 'to',
        chr(10277): 'us',
        chr(10279): 'very',
        chr(10292): 'was',
        chr(10302): 'with',
        chr(10298): 'will',
        chr(10301): 'you',
        }

punctuation_A = {
        chr(10242): ',',
        chr(10246): ';',
        chr(10258): ':',
        chr(10290): '.',
        chr(10262): '!',
        chr(10294): '()',
        chr(10278): '“',
        chr(10292): '”',
        chr(10252): '/',
        chr(10300): '#',
        chr(10244): '\'',
        chr(10276): '-',
        }

numbers_A = {
        chr(10241): '1',
        chr(10243): '2',
        chr(10249): '3',
        chr(10265): '4',
        chr(10257): '5',
        chr(10251): '6',
        chr(10267): '7',
        chr(10259): '8',
        chr(10250): '9',
        chr(10266): '0',
        }
